# servicio interno para java
# Europa
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shipments-master
  name: shipments-master-svc
spec:
  type: NodePort
  ports:
    - name: tomcat-port
      port: 8080
      protocol: TCP
  selector:
    app: shipments-master