apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  vault_url: "http://vault:8200"
  vault_jwt_path: "/var/run/secrets/kubernetes.io/serviceaccount/token"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipments-master
  labels:
    app: shipments-master
    version: 1.0.4
spec:
  selector:
    matchLabels:
      app: shipments-master
  replicas: 1
  template:
    metadata:
      labels:
        app: shipments-master
    spec:
      serviceAccountName: vault
      containers:
        - name: shipments-master
          image: citizenkaraba/shipments-master
          imagePullPolicy: Always
          env:
            - name: VAULT_URL
              valueFrom:
                configMapKeyRef:
                  name: vault-config
                  key: vault_url
            - name: VAULT_JWT_PATH
              valueFrom:
                configMapKeyRef:
                  name: vault-config
                  key: vault_jwt_path
          ports:
            - containerPort: 8080
